df <- read.table("household_power_consumption.txt", sep=";", header = TRUE, na.strings=("?"))
df1 <- subset(df, df$Date == "1/2/2007" )
df2 <- subset(df, df$Date == "2/2/2007" )
final <- rbind(df1,df2)
png("plot3.png", width=480, height=480)
library(ggplot2)
theme_set(theme_minimal())
final$DT <- paste(final$Date,final$Time)
final$y <- strptime(final$DT, format='%d/%m/%Y %H:%M:%S')
plot(final$y, final$Sub_metering_1, type="l", ylab="Energy sub metering", xlab = "")
lines(final$y,final$Sub_metering_2, lwd=2, col="red")
lines(final$y,final$Sub_metering_3, lwd=2, col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), 
       lwd=c(2,2,2), col=c("black","blue","red"))
dev.off()