df <- read.table("household_power_consumption.txt", sep=";", header = TRUE, na.strings=("?"))
df1 <- subset(df, df$Date == "1/2/2007" )
df2 <- subset(df, df$Date == "2/2/2007" )
final <- rbind(df1,df2)
png("plot2.png", width=480, height=480)
final$DT <- paste(final$Date,final$Time)
y <- strptime(final$DT, format='%d/%m/%Y %H:%M:%S')
plot(y, final$Global_active_power, type="l", ylab="Global Active Power (kilowatts)", xlab = "")
dev.off()
